version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pytest
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  build_and_test:
    jobs:
      - build